import { createStitches } from '@stitches/react';
import { TTypes } from 'src/@types';

export const { styled, css } = createStitches({
	theme: {
		colors: {
			dark: '#333',
			light: '#fff',
			darkGray: '#212121',
			mediumGray: '#666',
			lightGray: '#e0e0e0',
			defaultGray: '#f7f7f7',

			typeEletric: '#F9CF30',
			typeBug: '#A6B91A',
			typeDark: '#705746',
			typeDragon: '#6F35FC',
			typeElectric: '#F7D02C',
			typeFairy: '#D685AD',
			typeFighting: '#C22E28',
			typeFire: '#EE8130',
			typeFlying: '#A98FF3',
			typeGhost: '#735797',
			typeGrass: '#7AC74C',
			typeGround: '#E2BF65',
			typeIce: '#96D9D6',
			typeNormal: '#A8A77A',
			typePoison: '#A33EA1',
			typePsychic: '#F95587',
			typeRock: '#B6A136',
			typeSteel: '#B7B7CE',
			typeWater: '#6390F0',
		},
		space: {
			1: '2px',
			2: '4px',
			3: '8px',
			4: '16px',
			5: '24px',
			6: '32px',
			7: '40px',
			8: '48px',
			9: '56px',
			10: '64px',
			11: '72px',
			12: '80px',
			14: '120px',
			15: '160px',
			16: '200px',
		},
		fontSizes: {
			xs: '0.5em',
			sm: '0.8em',
			default: '1em',
			md: '1.2em',
			lg: '1.6em',
			xl: '2em',
			xxl: '3em',
		},
		fonts: {
			default: 'Poppins, sans-serif',
		},
		fontWeights: {
			regular: '400',
			semi: '600',
			bold: '700',
		},
		lineHeights: {},
		letterSpacings: {},
		sizes: {
			1: '2px',
			2: '4px',
			3: '8px',
			4: '16px',
			5: '24px',
			6: '32px',
			7: '40px',
			8: '48px',
			9: '56px',
			10: '64px',
			11: '72px',
			12: '80px',
			14: '120px',
			15: '160px',
			16: '200px',
		},
		borderWidths: {},
		borderStyles: {},
		radii: {
			sm: '4px',
			default: '8px',
			md: '12px',
			lg: '16px',
			xl: '24px',
			pill: '100%',
		},
		shadows: {},
		zIndices: {},
		transitions: {},
	},
});

export const typeColor = (type: TTypes): string => {
	const allTypes = {
		bug: '$typeBug',
		dark: '$typeDark',
		dragon: '$typeDragon',
		electric: '$typeElectric',
		fairy: '$typeFairy',
		fighting: '$typeFighting',
		fire: '$typeFire',
		flying: '$typeFlying',
		ghost: '$typeGhost',
		grass: '$typeGrass',
		ground: '$typeGround',
		ice: '$typeIce',
		normal: '$typeNormal',
		poison: '$typePoison',
		psychic: '$typePsychic',
		rock: '$typeRock',
		steel: '$typeSteel',
		water: '$typeWater',
		unknown: '$typeNormal',
		shadow: '$typeNormal',
	};

	return allTypes[type];
};
